### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'Device'

### ISSUE THREAD

**Issue by dtch1997** [ethanluoyc/optimal_transport_reward#2]
I followed the instructions to install dependencies and run the training script, but I encountered an error. I don't normally use Jax so I'm unsure why this happens. 

System details: Ubuntu 22.04, Python 3.8. Dependencies installed in Conda environment with `python -m pip install -r requirements/base.txt` 

Error message:
```bash
$ python -m otr.train_offline \
    --workdir /tmp/otr \
    --config otr/configs/otil_iql_mujoco.py \
    --config.expert_dataset_name='hopper-medium-replay-v2' \
    --config.k=10 \
    --config.offline_dataset_name='hopper-medium-replay-v2' \
    --config.use_dataset_reward=True
Traceback (most recent call last):
  File "/home/daniel/anaconda3/envs/otr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/daniel/anaconda3/envs/otr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/daniel/Documents/github/optimal_transport_reward/otr/train_offline.py", line 6, in <module>
    from acme.agents.jax import actor_core as actor_core_lib
  File "/home/daniel/anaconda3/envs/otr/lib/python3.9/site-packages/acme/agents/jax/actor_core.py", line 21, in <module>
    from acme.jax import networks as networks_lib
  File "/home/daniel/anaconda3/envs/otr/lib/python3.9/site-packages/acme/jax/networks/__init__.py", line 17, in <module>
    from acme.jax.networks.atari import AtariTorso
  File "/home/daniel/anaconda3/envs/otr/lib/python3.9/site-packages/acme/jax/networks/atari.py", line 27, in <module>
    from acme.jax.networks import base
  File "/home/daniel/anaconda3/envs/otr/lib/python3.9/site-packages/acme/jax/networks/base.py", line 23, in <module>
    from acme.jax import utils as jax_utils
  File "/home/daniel/anaconda3/envs/otr/lib/python3.9/site-packages/acme/jax/utils.py", line 149, in <module>
    device: Optional[jax.Device] = None,
AttributeError: module 'jax' has no attribute 'Device'
```

**Comment by ethanluoyc** [comment]
This looks like an issue with an Acme version update. I forgot to pin the version of acme in requirements.

Can you try installing acme with version from here https://github.com/deepmind/acme/commit/bee0cebc7608e91f0ca667f846db00dc6187c3cf ?

**Comment by ethanluoyc** [comment]
The acme version on PyPI is quite old so I won't recommend that. In this case, can you try change `class OTILBuilder(builders.ActorLearnerBuilder[DirectRLNetworks,...` to `class OTILBuilder(builders.ActorLearnerBuilder`.

I normally use Acme at HEAD and sometimes they do tend to introduce breaking changes...

**Comment by tlatjddnd101** [comment]
@dtch1997 I solved this issue by `pip install dm-acme[jax,tf]`, which arrives to install Jax and TensorFlow again.

**Comment by dara1400** [comment]
> @dtch1997 I solved this issue by `pip install dm-acme[jax,tf]`, which arrives to re-install Jax. More precisely, the version of Jax should be higher than equal to 0.4.3.

Thanks for you comments
I have done this and the mentioned error is fixed, but new error has emerged:

TypeError: <class 'acme.agents.jax.builders.ActorLearnerBuilder'> is not a generic class

**Comment by ethanluoyc** [comment]
I will do a pass over the dependency to fix this for everyone. With the updated dependency, there might be reduced reproducibility with updated dependency though.

**Comment by ethanluoyc** [comment]
I updated the repository to fix the issue. It should work now. Please follow the updated README.md for instructions.

Please open another issue if problems persist.
