### ISSUE TITLE
ERROR: No matching distribution found for jaxlib==0.4.19+cuda11.cudnn86

### ISSUE THREAD

**Issue by dara1400** [ethanluoyc/optimal_transport_reward#4]
Thanks for following the last issue.
I encounter a new error:
	ERROR: No matching distribution found for jaxlib==0.4.19+cuda11.cudnn86

**Comment by dara1400** [comment]
It is fixed by :
pip install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.4.19+cuda11.cudnn86-cp310-cp310-manylinux2014_x86_64.whl

**Comment by ethanluoyc** [comment]
Should be fixed by [006e910](https://github.com/ethanluoyc/optimal_transport_reward/commit/006e910a1d84c94bf855480328c490444bd4517b)
